const map = new Map()
    .set(0, "Clear sky")
    .set(1, "Mainly clear")
    .set(2, "Partly cloudy")
    .set(3, "Overcast")
    .set(45, "Fog")
    .set(48, "Depositing rime fog")
    .set(51, "Light drizzle")
    .set(53, "Moderate drizzle")
    .set(55, "Dense drizzle")
    .set(56, "Light freezing drizzle")
    .set(57, "Dense freezing drizzle")
    .set(61, "Slight rain")
    .set(63, "Moderate rain")
    .set(65, "Heavy rain")
    .set(66, "Light freezing rain")
    .set(67, "Heavy freezing rain")
    .set(71, "Slight snowfall")
    .set(73, "Moderate snowfall")
    .set(75, "Heavy snowfall")
    .set(77, "Snow grains")
    .set(80, "Slight rain shower")
    .set(81, "Moderate rain shower")
    .set(82, "Violent rain shower")
    .set(85, "Slight snow shower")
    .set(86, "Heavy snow shower")

    export default map